# Example of a permissive access policy, except no deletes.
kind: BucketAccessClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: account1-permissive-no-deletes
driverName: s3-iam.objectstorage.k8s.io
authenticationType: KEY
parameters:
  accountSecret: s3-account1
  accountSecretNamespace: s3-iam-cosi-driver
  iamUserPattern: "cosi-${bucketAccessName}-${random}"

  # Users are granted all actions on buckets (by default or by request)
  defaultPolicy:
    allow:
      actions:
        - "s3:*"
  requestPolicy:
    allow:
      actions:
        - "s3:*"
    # Only deletes are denied
    deny:
      actions:
        - "s3:DeleteObject"

  # No other actions are denied
---
# By default, this request is granted all S3 actions (except deletes).
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: my-bucket1-access
  namespace: default
spec:
  bucketClaimName: my-bucket1
  bucketAccessClassName: account1-permissive-no-deletes
  credentialsSecretName: my-bucket1-credentials
  protocol: s3
---
# This request will get denied because it requests delete action.
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: my-bucket1-access
  namespace: default
spec:
  bucketClaimName: my-bucket1
  bucketAccessClassName: account1-permissive-no-deletes
  credentialsSecretName: my-bucket1-credentials
  protocol: s3
  accessRequest:
    actions:
      - "s3:DeleteObject"