apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s3-iam-cosi-driver

generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated-by: "kustomize"

resources:
- ns.yaml
- sa.yaml
- rbac.yaml
- deployment.yaml
