apiVersion: v1
kind: Secret
metadata:
  name: s3-account1
  namespace: s3-iam-cosi-driver
type: Opaque
data:
  # All values are converted to base64
  # i.e. echo -n "value" | base64
  Endpoint: S3_ENDPOINT
  S3Port: S3_PORT
  IAMPort: IAM_PORT
  AccountName: ACCOUNT_NAME
  AccessKey: ACCOUNT_ACCESS_KEY
  SecretKey: ACCOUNT_SECRET_KEY
  TlsCert: TLS_CERT
